{"name": "Проверяем, что курьер не может залогиниться с невалидным логином и паролем, запрос возвращает ошибку с кодом 400", "status": "passed", "start": 1727466559510, "stop": 1727466559635, "uuid": "c7effe89-2125-48ba-9653-7c6cfc8fc7b0", "historyId": "2636fb33f2c2bdf15efc2cceb3ae4f78", "testCaseId": "2636fb33f2c2bdf15efc2cceb3ae4f78", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_not_existing_user_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "hanastasia-mbby"}, {"name": "thread", "value": "97967-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}